"""F9.0 — Candidate / CandidateMetrics / CandidateResult.

The atomic unit of the LERO loop is a Candidate: one (compute_reward,
enhance_observation) pair generated by the LLM. After short training each
candidate produces CandidateMetrics; the pair is bundled as
CandidateResult, which is what the prompt composer's feedback iterates
over and what the orchestrator ranks for the full-training fallback chain.

Pure-domain. No torch, no LiteLLM. Strings stay as strings — the AST
validator (F9.4) and the scenario patcher (F9.5) are the ones that
``compile()`` them inside their respective adapters.
"""

from typing import Literal

from pydantic import BaseModel, Field

from multi_scenario.domain.models._common import STRICT


#: Tri-state outcome of a candidate's short-training evaluation, ranked
#: from worst to best so the prompt composer can sort by it directly:
#: - ``invalid`` — failed AST / patching / training crashed.
#: - ``regression`` — completed, but eval-M1 worse than the iteration baseline.
#: - ``flat`` — completed, eval-M1 unchanged from baseline.
#: - ``progress`` — completed, eval-M1 strictly above baseline.
#:
#: We keep this as a Literal alias rather than a Pydantic Enum so it
#: serialises as a plain string in JSON traces — easier to grep, easier
#: to hand-edit when post-hoc analysis surfaces a missing verdict.
Verdict = Literal["invalid", "regression", "flat", "progress"]


class CandidateCode(BaseModel):
    """The raw LLM-generated source code for one candidate.

    Either ``reward_source`` or ``obs_source`` may be ``None`` when the
    LERO config disabled that evolution target (``evolve_reward=False``
    or ``evolve_observation=False``). At least one is guaranteed
    non-None by F9.4's ``extract_candidates``.
    """

    model_config = STRICT

    reward_source: str | None = None
    obs_source: str | None = None
    #: The raw LLM response text the codegen extracted from. Stored for
    #: provenance — lets us regenerate / re-validate without re-asking
    #: the LLM (free reproducibility).
    raw_response: str = Field(default="")


class CandidateMetrics(BaseModel):
    """M1–M9 dict + LERO-specific eval scalars after short training.

    Mirrors the existing :class:`MetricRecord`-like shape but as a
    Pydantic model rather than a list, so the prompt composer can do
    ``metrics.M1_success_rate`` directly. ``None`` for any metric the
    scenario didn't compute (e.g., M5 outside comm scenarios).
    """

    model_config = STRICT

    M1_success_rate: float | None = None
    M2_avg_return: float | None = None
    M3_steps: float | None = None
    M4_collisions: float | None = None
    M5_tokens: float | None = None
    M6_coverage_progress: float | None = None
    M7_sample_efficiency: float | None = None
    M8_agent_utilization: float | None = None
    M9_spatial_spread: float | None = None


class Candidate(BaseModel):
    """Identity + code for one LERO candidate.

    Identity = ``(iteration, candidate_idx)``: the prompt composer uses
    this to thread per-(iter, cand) seeds through the LLM call so sibling
    candidates aren't textually identical at temperature=1.0. The
    rendezvous_comm trick (sha256(run_id|seed|iter|cand|level) % 2**31)
    is implemented in the orchestrator, not here, so this stays
    pure-data.
    """

    model_config = STRICT

    iteration: int = Field(ge=0)
    candidate_idx: int = Field(ge=0)
    code: CandidateCode


class CandidateResult(BaseModel):
    """Candidate + Metrics + Verdict — what the composer's feedback ranks.

    The orchestrator's fallback chain (F9.6) sorts a list of these by
    ``(verdict_rank, M1, M6, M2)`` (descending) when picking which
    candidate to full-train. ``verdict_rank`` maps:
    invalid<regression<flat<progress so progress always wins ties.
    """

    model_config = STRICT

    candidate: Candidate
    metrics: CandidateMetrics
    verdict: Verdict
    #: Free-form blurb from the orchestrator — typically a brief
    #: human-readable note like "M1 = 0.32 vs baseline 0.10 →
    #: progress" or "training crashed: NaN actions @ iter 12".
    note: str = ""
