"""Code extraction, validation, and feedback formatting.

Parses LLM output into executable Python functions.
Independent of how the LLM was called (raw SDK or future DSPy).
"""

import ast
import logging
import re
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

from .prompts.loader import PromptLoader

_log = logging.getLogger("rendezvous.lero")

# Imports allowed inside LLM-generated code
ALLOWED_IMPORTS = {"torch", "math", "numpy"}

# Regex to extract ```python ... ``` blocks
_CODE_BLOCK_RE = re.compile(
    r"```python\s*\n(.*?)```", re.DOTALL
)


@dataclass
class CandidateCode:
    """One (reward_fn, obs_fn) pair generated by the LLM."""

    reward_source: Optional[str]  # None if evolve_reward=False
    obs_source: Optional[str]     # None if evolve_observation=False
    raw_response: str             # Full LLM response for provenance

    @property
    def source(self) -> str:
        """Combined source for display / feedback."""
        parts = []
        if self.reward_source:
            parts.append(self.reward_source)
        if self.obs_source:
            parts.append(self.obs_source)
        return "\n\n".join(parts)


def extract_candidates(
    responses: List[str],
    evolve_reward: bool = True,
    evolve_observation: bool = True,
) -> List[CandidateCode]:
    """Extract and validate candidate code from LLM responses.

    Each response should contain up to two ```python blocks:
    one for compute_reward and one for enhance_observation.

    Returns only candidates that pass AST validation.
    """
    candidates = []
    for resp in responses:
        code_blocks = _CODE_BLOCK_RE.findall(resp)
        if not code_blocks:
            _log.warning("No code blocks found in LLM response")
            continue

        reward_src = None
        obs_src = None

        for block in code_blocks:
            block = block.strip()
            if "def compute_reward" in block and evolve_reward:
                if validate_function(
                    block, "compute_reward", ["scenario_state"]
                ):
                    reward_src = block
                else:
                    _log.warning("compute_reward failed validation")
            elif "def enhance_observation" in block and evolve_observation:
                if validate_function(
                    block, "enhance_observation", ["scenario_state"]
                ):
                    obs_src = block
                else:
                    _log.warning("enhance_observation failed validation")

        # Accept if at least one requested function was found
        if (evolve_reward and reward_src is None
                and evolve_observation and obs_src is None):
            _log.warning("No valid functions extracted from response")
            continue

        candidates.append(CandidateCode(
            reward_source=reward_src,
            obs_source=obs_src,
            raw_response=resp,
        ))

    return candidates


def validate_function(
    source: str,
    expected_name: str,
    expected_args: List[str],
) -> bool:
    """Validate a generated function via AST parsing.

    Checks:
    - Parses as valid Python
    - Contains a function with the expected name
    - Function has the expected arguments
    - No imports outside the allowlist
    """
    try:
        tree = ast.parse(source)
    except SyntaxError as e:
        _log.warning("Syntax error in generated code: %s", e)
        return False

    # Find the target function
    func_def = None
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == expected_name:
            func_def = node
            break

    if func_def is None:
        _log.warning("Function '%s' not found in code", expected_name)
        return False

    # Check arguments
    actual_args = [a.arg for a in func_def.args.args]
    if actual_args != expected_args:
        _log.warning(
            "Function '%s' args %s != expected %s",
            expected_name, actual_args, expected_args,
        )
        return False

    # Check imports
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                module = alias.name.split(".")[0]
                if module not in ALLOWED_IMPORTS:
                    _log.warning("Disallowed import: %s", alias.name)
                    return False
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                module = node.module.split(".")[0]
                if module not in ALLOWED_IMPORTS:
                    _log.warning("Disallowed import from: %s", node.module)
                    return False

    return True


def build_feedback(
    candidates: List[CandidateCode],
    metrics_list: List[Dict],
    top_k: int,
    prompt_loader: PromptLoader,
    task_params: Dict,
) -> str:
    """Format feedback for the next evolutionary iteration.

    Args:
        candidates: candidate code objects
        metrics_list: M1-M9 metrics for each candidate
        top_k: number of top candidates to include in feedback
        prompt_loader: template loader
        task_params: task parameters for template rendering
    """
    # Sort by fitness (M1 primary, M2 secondary)
    indexed = list(enumerate(zip(candidates, metrics_list)))
    indexed.sort(
        key=lambda x: (
            x[1][1].get("M1_success_rate", 0),
            x[1][1].get("M2_avg_return", -1e9),
        ),
        reverse=True,
    )

    # Build results text
    lines = []
    for rank, (orig_idx, (cand, metrics)) in enumerate(indexed):
        lines.append(f"--- Candidate #{orig_idx + 1} (rank {rank + 1}) ---")
        lines.append(f"M1 Success Rate:    {metrics.get('M1_success_rate', 0):.3f}")
        lines.append(f"M2 Avg Return:      {metrics.get('M2_avg_return', 0):.2f}")
        lines.append(f"M4 Avg Collisions:  {metrics.get('M4_avg_collisions', 0):.2f}")
        lines.append(f"M6 Coverage:        {metrics.get('M6_coverage_progress', 0):.3f}")
        if "M5_avg_tokens" in metrics and metrics["M5_avg_tokens"] > 0:
            lines.append(f"M5 Avg Tokens:      {metrics.get('M5_avg_tokens', 0):.1f}")
        lines.append("")
        if cand.reward_source:
            lines.append("Reward function:")
            lines.append(f"```python\n{cand.reward_source}\n```")
        if cand.obs_source:
            lines.append("Observation enhancement:")
            lines.append(f"```python\n{cand.obs_source}\n```")
        lines.append("")

    best_idx = indexed[0][0] + 1  # 1-indexed

    # Comm-specific metrics line
    has_comm = any(
        m.get("M5_avg_tokens", 0) > 0 for m in metrics_list
    )
    comm_metrics = (
        "- M5 (Avg Tokens): communication messages per episode. "
        "Balance informativeness vs bandwidth cost."
        if has_comm else ""
    )

    return prompt_loader.render(
        "feedback.txt",
        n_candidates=len(candidates),
        n_agents=task_params.get("n_agents", 4),
        n_targets=task_params.get("n_targets", 4),
        agents_per_target=task_params.get("agents_per_target", 2),
        candidates_results="\n".join(lines),
        best_idx=best_idx,
        comm_metrics=comm_metrics,
    )
